# Generated by Django 5.2 on 2025-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='absent', max_length=10),
        ),
    ]
