# Generated by Django 5.2 on 2025-05-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandence', '0002_employeeattendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='status',
        ),
    ]
